### ISSUE TITLE
Question: How does handshake timeout work?

### ISSUE THREAD

**Issue by jacob-pro** [tmccombs/tls-listener#16]
Please forgive me I'm not very knowledgeable on the whole TLS handshake process...

But I'm wondering should this crate add a timeout to the TLS accept(), or is this typically built in to the TLS library (I had a look through the docs but couldn't see how to configure this with tokio-rustls / tokio-native-tls ) ?

If there is no timeout configured could it potentially lead to a DDoS vulnerability, where no more handshakes are able to be processed?

Either way it may be good to add some comments about this in the documentation?

**Comment by jacob-pro** [comment]
The equivalent utility in actix-net sets its own timeout:
https://github.com/actix/actix-net/blob/master/actix-tls/src/accept/native_tls.rs#L95

**Comment by jacob-pro** [comment]
Sorry I completely missed that this is already implemented!

**Comment by tmccombs** [comment]
For the sake of posterity, this is configurable using [`Builder::handshake_timeout`](https://docs.rs/tls-listener/latest/tls_listener/struct.Builder.html#method.handshake_timeout).
