### ISSUE TITLE
Question about Parallelism

### ISSUE THREAD

**Issue by jacob-pro** [tmccombs/tls-listener#17]
Sorry if this is another silly question, but I was wondering how the concurrency/parrallelism works.

I realise we are using FuturesUnordered to poll the accept handshakes - but as far as I understand while it will work concurrently, it will never perform any work in parrallel / on multiple CPU threads, since they are all part of the same "task".

Would it be a good idea to first spawn the futures so they can run as parallel tasks?

**Comment by tmccombs** [comment]
Well, I think #18 works. Unfortunately, it isn't as ergonomic as I'd like due to the inability of rust to infer the type parameters.

**Comment by tmccombs** [comment]
If you have any ideas on how to improve it, or better names for the method and types, I'd love to hear it.

**Comment by jacob-pro** [comment]
Hi,
I think I may have discovered an issue with the current implemenation?
We seem to be doing timeout wrapped around the JoinHandle,  does this mean that the underlying accept future will never timeout / can stay around forever ?
I think we need to do the timeout inside the task?

**Comment by tmccombs** [comment]
I think #22 might fix that.
