### ISSUE TITLE
example building fails

### ISSUE THREAD

**Issue by qianzhang5** [tmccombs/tls-listener#26]
cargo build --examples

error[E0432]: unresolved import `tls_config::tls_acceptor`
  --> examples/echo.rs:12:5
   |
12 | use tls_config::tls_acceptor;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `tls_acceptor` in `tls_config`

error[E0412]: cannot find type `TlsStream` in this scope
  --> examples/echo.rs:15:32
   |
15 | async fn handle_stream(stream: TlsStream<TcpStream>) {
   |                                ^^^^^^^^^ help: a struct with a similar name exists: `TcpStream`
   |

**Comment by qianzhang5** [comment]
I figured out that default example build needs to change features in Cargo.toml.  It's better to those features in default.

**Comment by tmccombs** [comment]
the `test_examples.py` script under examples will buidl the examples with the right features enabled. Unfortunately, I don't know of a way to add default features to examples without adding them to the library's default features. 

When adding tls-listener as a dependency of another project you will probably want to enable at least one of the tls backend features (`rustls`, `native-tls`, or `openssl`).

**Comment by qianzhang5** [comment]
Thanks you, I understand now It's a python based example build/test system.
