### ISSUE TITLE
hyper server exits when you connect with http

### ISSUE THREAD

**Issue by miquels** [tmccombs/tls-listener#3]
I added TLS support to one of my hyper-based projects using tls-listener. It works fine. But when I accidentally connected with http instead of https, the server exited with this error:

```
error accepting connection: received corrupt message
```

I think it would be better if TlsListener just ignored failed TLS connections, instead of exiting with an error.

**Comment by tmccombs** [comment]
This is mentioned [here](https://github.com/tmccombs/tls-listener/blob/main/examples/http.rs#L20). 

https://github.com/tmccombs/tls-listener/blob/main/examples/http-low-level.rs also shows an example of a way to handle bad connections. 

The idea is that is up to the user on how to handle errors such as invalid TLS connections. 

Maybe this should be better documented in the doc comments. 

I might also be ok with having a way to make it easier to handle errors, although at the moment I'm not sure what a good design for that would be that would still allow flexibility to log errors as well.

**Comment by miquels** [comment]
Ok, that's clear enough. Thanks!
