### ISSUE TITLE
Consider releasing `0.10.2` or `0.11.0`?

### ISSUE THREAD

**Issue by fuzzypixelz** [tmccombs/tls-listener#47]
It would be useful to get the changes introduced in #46. It seems that even if I set `tokio-rustls` to not use `aws-lc-rs`, this dependency would still be pulled in by the `rustls` feature of `tls-listener`.

According to the [Cargo SemVer policy](https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-add) this _technically_ would be a minor release, I don't know if you disagree.

Thanks in advance :)

**Comment by tmccombs** [comment]
Sorry, I thought I had already done that.

Done now

**Comment by fuzzypixelz** [comment]
> Sorry, I thought I had already done that.
> 
> Done now

Thanks!
