### ISSUE TITLE
Support for native-tls

### ISSUE THREAD

**Issue by jacob-pro** [tmccombs/tls-listener#6]
Hi, 

Thanks for this crate, it looks really useful. 

I can see the current implementation uses rustls - but  I really need to be able to use native-tls instead. 

Can you see any technical reasons why this would be difficult to implement, and would you be willing to accept a pull request if I implement this such that there is a rustls and native-tls cargo feature flag?

**Comment by tmccombs** [comment]
I remember considering it but thought the complexity of supporting both wasn't worth the time, at least initially. 

If you make a PR that adds the feature without adding too much complexity I would probably be open to accepting it. 

One potential point of concern is that cargo doesn't currently handle mutually exclusive feature flags very well, and I'm worried that supporting both rustls and native-tls at the same time could make the API more complicated (for example, needing to make the `Builder` struct generic), and possibly break backwards compatibility.

**Comment by jacob-pro** [comment]
Resolved in https://github.com/tmccombs/tls-listener/commit/50a568226feb77e0f220a2ab0dab90d85135276f thanks @tmccombs
