### ISSUE TITLE
Tlslistener send

### ISSUE THREAD

**Issue by uglyoldbob** [tmccombs/tls-listener#9]
How hard would it be to make the tlslistener struct Send (the trait)?

**Comment by thepperson** [comment]
Oh wait, I think it is AddrIncoming that is not send

**Comment by uglyoldbob** [comment]
I have a repo where I am trying to use tokio::spawn, which is requiring Send.
during the build ->
> has type `TlsListener<AddrIncoming, tokio_native_tls::TlsAcceptor>` which is not `Send`

https://github.com/uglyoldbob/iot

**Comment by tmccombs** [comment]
I think https://github.com/tmccombs/tls-listener/pull/10/files would do it.

**Comment by uglyoldbob** [comment]
Yes that solved it. Thank you!
